CREATE OR REPLACE PACKAGE RENTAL AS

    TYPE ID_ARRAY IS TABLE OF NUMBER(10);
    
    TYPE AUTHOR_RECORD IS RECORD(FIRST_NAME VARCHAR2(100), LAST_NAME MK.AUTHORS.LAST_NAME%TYPE, BIRTH_DATE DATE, DEATH_DATE DATE);
    
    TYPE TITLE_RECORD IS RECORD(TITLE VARCHAR2(250), PUB_DATE DATE, AGE_LIMIT NUMBER(2), TITLE_DESCRIPTION BLOB);
    
    TYPE AUTHOR_TITLE_RECORD IS RECORD(AUTHOR_ID NUMBER(10), TITLE_ID NUMBER(10));
    
    TYPE LOCATION_SPOTS IS RECORD(LOCATION_ID NUMBER(10), NUMBER_OF_EMPTY_SPOTS NUMBER);
    
    TYPE LOCATIONS_DICTIONARY IS TABLE OF LOCATION_SPOTS;
    
    LOCATIONS_CORRIDOR_NUMBER CONSTANT NUMBER := 10;
    LOCATIONS_RACK_NUMBER CONSTANT NUMBER := 15;
    LOCATIONS_SHELF_NUMBER CONSTANT NUMBER := 8;
    LOCATIONS_BOOKS_ON_SHELF CONSTANT NUMBER := 12;
    
    TYPE BOOK_RECORD IS RECORD(TITLE_ID NUMBER, LOCATION_ID NUMBER, BOOK_VALUE NUMBER, CONDITION NUMBER, BUY_DATE DATE);
    
    -- ==================================================================

    FUNCTION SEARCH_AUTHOR(AUTHOR_TO_SEARCH AUTHOR_RECORD) RETURN NUMBER;
    
    FUNCTION SEARCH_AUTHOR(FIRST_NAME VARCHAR2, LAST_NAME VARCHAR2, BIRTH_DATE DATE, DEATH_DATE DATE) 
        RETURN NUMBER;
    
    FUNCTION ADD_AUTHOR(AUTHOR_TO_ADD AUTHOR_RECORD) 
        RETURN NUMBER;
    
    FUNCTION ADD_AUTHOR(FIRST_NAME VARCHAR2, LAST_NAME VARCHAR2, BIRTH_DATE DATE, DEATH_DATE DATE) 
        RETURN NUMBER;
    
    FUNCTION PICK_AUTHOR(PICKED_AUTHOR_ID NUMBER, AUTHOR_TO_PICK AUTHOR_RECORD) 
        RETURN NUMBER;
        
    FUNCTION PICK_AUTHOR(PICKED_AUTHOR_ID NUMBER, FIRST_NAME VARCHAR2, LAST_NAME VARCHAR2, BIRTH_DATE DATE, DEATH_DATE DATE)
        RETURN NUMBER;
    
    FUNCTION SEARCH_TITLE(TITLE_TO_SEARCH TITLE_RECORD) 
        RETURN NUMBER;
        
    FUNCTION SEARCH_TITLE(TITLE VARCHAR2, PUB_DATE DATE, AGE_LIMIT NUMBER, TITLE_DESCRIPTION BLOB)
        RETURN NUMBER;
    
    FUNCTION ADD_TITLE(TITLE_TO_ADD TITLE_RECORD) 
        RETURN NUMBER;
        
    FUNCTION ADD_TITLE(TITLE VARCHAR2, PUB_DATE DATE, AGE_LIMIT NUMBER, TITLE_DESCRIPTION BLOB)
        RETURN NUMBER;
    
    FUNCTION PICK_TITLE(PICKED_TITLE_ID NUMBER, TITLE_TO_PICK TITLE_RECORD) 
        RETURN NUMBER;
        
    FUNCTION PICK_TITLE(PICKED_TITLE_ID NUMBER, TITLE VARCHAR2, PUB_DATE DATE, AGE_LIMIT NUMBER, TITLE_DESCRIPTION BLOB)
        RETURN NUMBER;
    
    FUNCTION AUTHORS_TITLES_RELATION(RELATION_AUTHORS ID_ARRAY, RELATION_TITLE_ID NUMBER) 
        RETURN NUMBER;
    
    PROCEDURE INITIATE_lOCATIONS;
    
    FUNCTION GET_LOCATION_LIST(BOOKS_AMOUNT NUMBER) 
        RETURN LOCATIONS_DICTIONARY;
    
    FUNCTION ADD_BOOKS(TITLE_ID NUMBER, HOW_MANY_BOOKS NUMBER, ADDED_BOOKS_LOCATIONS LOCATIONS_DICTIONARY, 
        ADDED_BOOKS_VALUE NUMBER, ADDED_BOOKS_CONDITION NUMBER, ADDED_BOOKS_BUY_DATE DATE) 
        RETURN ID_ARRAY;
    
END RENTAL;
/



















