CREATE TABLE AUTHORS(
    AUTHOR_ID NUMBER(10) GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1), 
    FIRST_NAME VARCHAR2(100) NULL,
    LAST_NAME VARCHAR2(100) NOT NULL,
    BIRTH_DATE DATE NULL,
    DEATH_DATE DATE NULL,
    WHO_ADDED VARCHAR2(70) DEFAULT USER NOT NULL,
    WHEN_ADDED TIMESTAMP DEFAULT SYSDATE NOT NULL,
    WHO_LAST_MOD VARCHAR2(70) NULL,
    WHEN_LAST_MOD TIMESTAMP NULL,
    CONSTRAINT AUTHORS_PK PRIMARY KEY (AUTHOR_ID),
    CONSTRAINT AUTHORS_CK_1 CHECK (BIRTH_DATE < DEATH_DATE)
);

CREATE INDEX AUTHORS_FIRST_NAME_IDX ON AUTHORS(UPPER(NVL(FIRST_NAME, '9438H45TG45')));

CREATE OR REPLACE TRIGGER AUTHORS_TRIG
BEFORE INSERT OR UPDATE ON AUTHORS FOR EACH ROW
DECLARE
    AUDIT_COL_INTERFERE EXCEPTION;
BEGIN
    IF 
        :NEW.WHO_ADDED != nvl(:OLD.WHO_ADDED, USER) OR 
        :NEW.WHEN_ADDED != nvl(:OLD.WHEN_ADDED, SYSDATE) OR
        :NEW.WHO_LAST_MOD != nvl(:OLD.WHO_LAST_MOD, '234234234') OR
        :NEW.WHEN_LAST_MOD != nvl(:OLD.WHEN_LAST_MOD, sysdate-1) THEN
            RAISE AUDIT_COL_INTERFERE;
    END IF;
    
    IF INSERTING THEN 
        :NEW.WHO_ADDED := USER;
        :NEW.WHEN_ADDED := SYSDATE;
    ELSIF UPDATING THEN
        :NEW.WHO_ADDED := :OLD.WHO_ADDED;
        :NEW.WHEN_ADDED := :OLD.WHEN_ADDED;
        :NEW.WHO_LAST_MOD := USER;
        :NEW.WHEN_LAST_MOD := SYSDATE;
    END IF;
EXCEPTION
    WHEN AUDIT_COL_INTERFERE THEN
        RAISE_APPLICATION_ERROR(-20101, 'AUTHORS TABLE: AN ATTEMPT TO INTERFERE WITH AN AUDIT COLUMN WAS MADE');
END;
/

-- =======================================================================

CREATE TABLE TITLES(
    TITLE_ID NUMBER(10) GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
    TITLE VARCHAR2(250) NOT NULL,
    PUB_DATE DATE NULL,
    AGE_LIMIT NUMBER(2) DEFAULT 7 NOT NULL,
    TITLE_DESCRIPTION BLOB NULL,
    WHO_ADDED VARCHAR2(70) DEFAULT USER NOT NULL,
    WHEN_ADDED TIMESTAMP DEFAULT SYSDATE NOT NULL,
    WHO_LAST_MOD VARCHAR2(70) NULL,
    WHEN_LAST_MOD TIMESTAMP NULL,
    CONSTRAINT TITLES_PK PRIMARY KEY (TITLE_ID),
    CONSTRAINT TITLES_CK_1 CHECK (AGE_LIMIT BETWEEN 7 AND 18)
);

CREATE OR REPLACE TRIGGER TITLES_TRIG
BEFORE INSERT OR UPDATE ON TITLES FOR EACH ROW
DECLARE
    AUDIT_COL_INTERFERE EXCEPTION;
BEGIN
    IF 
        :NEW.WHO_ADDED != nvl(:OLD.WHO_ADDED, USER) OR 
        :NEW.WHEN_ADDED != nvl(:OLD.WHEN_ADDED, SYSDATE) OR
        :NEW.WHO_LAST_MOD != nvl(:OLD.WHO_LAST_MOD, '234234234') OR
        :NEW.WHEN_LAST_MOD != nvl(:OLD.WHEN_LAST_MOD, sysdate-1) THEN
            RAISE AUDIT_COL_INTERFERE;
    END IF;
    
    IF INSERTING THEN 
        :NEW.WHO_ADDED := USER;
        :NEW.WHEN_ADDED := SYSDATE;
    ELSIF UPDATING THEN
        :NEW.WHO_ADDED := :OLD.WHO_ADDED;
        :NEW.WHEN_ADDED := :OLD.WHEN_ADDED;
        :NEW.WHO_LAST_MOD := USER;
        :NEW.WHEN_LAST_MOD := SYSDATE;
    END IF;
EXCEPTION
    WHEN AUDIT_COL_INTERFERE THEN
        RAISE_APPLICATION_ERROR(-20101, 'TITLES TABLE: AN ATTEMPT TO INTERFERE WITH AN AUDIT COLUMN WAS MADE');
END;
/

-- =======================================================================

CREATE TABLE AUTHORS_TITLES(
    AUTHOR_ID NUMBER(10) NOT NULL,
    TITLE_ID NUMBER(10) NOT NULL,
    WHO_ADDED VARCHAR2(70) DEFAULT USER NOT NULL,
    WHEN_ADDED TIMESTAMP DEFAULT SYSDATE NOT NULL,
    WHO_LAST_MOD VARCHAR2(70) NULL,
    WHEN_LAST_MOD TIMESTAMP NULL,
    CONSTRAINT AUTHORS_TITLES_PK PRIMARY KEY (AUTHOR_ID, TITLE_ID),
    CONSTRAINT AUTHORS_TITLES_FK_1 FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID),
    CONSTRAINT AUTHORS_TITLES_FK_2 FOREIGN KEY (TITLE_ID) REFERENCES TITLES(TITLE_ID)
);

CREATE OR REPLACE TRIGGER AUTHORS_TITLES_TRIG
BEFORE INSERT OR UPDATE ON AUTHORS_TITLES FOR EACH ROW
DECLARE
    AUDIT_COL_INTERFERE EXCEPTION;
BEGIN
    IF 
        :NEW.WHO_ADDED != nvl(:OLD.WHO_ADDED, USER) OR 
        :NEW.WHEN_ADDED != nvl(:OLD.WHEN_ADDED, SYSDATE) OR
        :NEW.WHO_LAST_MOD != nvl(:OLD.WHO_LAST_MOD, '234234234') OR
        :NEW.WHEN_LAST_MOD != nvl(:OLD.WHEN_LAST_MOD, sysdate-1) THEN
            RAISE AUDIT_COL_INTERFERE;
    END IF;
    
    IF INSERTING THEN 
        :NEW.WHO_ADDED := USER;
        :NEW.WHEN_ADDED := SYSDATE;
    ELSIF UPDATING THEN
        :NEW.WHO_ADDED := :OLD.WHO_ADDED;
        :NEW.WHEN_ADDED := :OLD.WHEN_ADDED;
        :NEW.WHO_LAST_MOD := USER;
        :NEW.WHEN_LAST_MOD := SYSDATE;
    END IF;
EXCEPTION
    WHEN AUDIT_COL_INTERFERE THEN
        RAISE_APPLICATION_ERROR(-20101, 'AUTHORS_TITLES TABLE: AN ATTEMPT TO INTERFERE WITH AN AUDIT COLUMN WAS MADE');
END;
/

-- =======================================================================

CREATE TABLE LOCATIONS(
    LOCATION_ID NUMBER(10) GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
    CORRIDOR NUMBER(2) NOT NULL,
    RACK NUMBER(2) NOT NULL,
    SHELF NUMBER(2) NOT NULL,
    EMPTY_SPOTS_LEFT NUMBER(10) DEFAULT 12 NOT NULL,
    WHO_ADDED VARCHAR2(70) DEFAULT USER NOT NULL,
    WHEN_ADDED TIMESTAMP DEFAULT SYSDATE NOT NULL,
    WHO_LAST_MOD VARCHAR2(70) NULL,
    WHEN_LAST_MOD TIMESTAMP NULL,
    CONSTRAINT LOCATIONS_PK PRIMARY KEY (LOCATION_ID)
);

CREATE OR REPLACE TRIGGER LOCATIONS_TRIG
BEFORE INSERT OR UPDATE ON LOCATIONS FOR EACH ROW
DECLARE
    AUDIT_COL_INTERFERE EXCEPTION;
BEGIN
    /*DBMS_OUTPUT.PUT_LINE(:old.when_added);
    DBMS_OUTPUT.PUT_LINE(:old.when_last_mod);
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE(:new.when_added);
    DBMS_OUTPUT.PUT_LINE(:new.when_last_mod);*/
    
    IF 
        :NEW.WHO_ADDED != nvl(:OLD.WHO_ADDED, USER) OR 
        :NEW.WHEN_ADDED != nvl(:OLD.WHEN_ADDED, SYSDATE) OR
        :NEW.WHO_LAST_MOD != nvl(:OLD.WHO_LAST_MOD, '234234234') OR
        :NEW.WHEN_LAST_MOD != nvl(:OLD.WHEN_LAST_MOD, sysdate-1) THEN
            RAISE AUDIT_COL_INTERFERE;
    END IF;
    
    IF INSERTING THEN 
        :NEW.WHO_ADDED := USER;
        :NEW.WHEN_ADDED := SYSDATE;
    ELSIF UPDATING THEN
        :NEW.WHO_ADDED := :OLD.WHO_ADDED;
        :NEW.WHEN_ADDED := :OLD.WHEN_ADDED;
        :NEW.WHO_LAST_MOD := USER;
        :NEW.WHEN_LAST_MOD := SYSDATE;
    END IF;
EXCEPTION
    WHEN AUDIT_COL_INTERFERE THEN
        RAISE_APPLICATION_ERROR(-20101, 'LOCATIONS TABLE: AN ATTEMPT TO INTERFERE WITH AN AUDIT COLUMN WAS MADE');
END;
/

-- =======================================================================

CREATE TABLE BOOKS(
    BOOK_ID NUMBER(10) GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
    TITLE_ID NUMBER(10) NOT NULL,
    BORROW_STATE VARCHAR2(70) NOT NULL,
    LOCATION_ID NUMBER(10) NULL,
    BOOK_VALUE NUMBER(10, 2) NOT NULL,
    CONDITION NUMBER(1) NOT NULL,
    BUY_DATE DATE NOT NULL,
    DELIVERY_ID NUMBER(10) NOT NULL,
    WHO_ADDED VARCHAR2(70) DEFAULT USER NOT NULL,
    WHEN_ADDED TIMESTAMP DEFAULT SYSDATE NOT NULL,
    WHO_LAST_MOD VARCHAR2(70) NULL,
    WHEN_LAST_MOD TIMESTAMP NULL,
    CONSTRAINT BOOKS_PK PRIMARY KEY (BOOK_ID),
    CONSTRAINT BOOKS_FK_1 FOREIGN KEY (TITLE_ID) REFERENCES TITLES(TITLE_ID),
    CONSTRAINT BOOKS_FK_2 FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID),
    CONSTRAINT BOOKS_FK_3 FOREIGN KEY (DELIVERY_ID) REFERENCES DELIVERIES(DELIVERY_ID),
    CONSTRAINT BOOKS_CK_1 CHECK (BORROW_STATE IN ('IN BORROW', 'IN STORAGE', 'LOST OR DESTROYED', 'STORAGE QUEUE')),
    CONSTRAINT BOOKS_CK_2 CHECK (BOOK_VALUE > 0),
    CONSTRAINT BOOKS_CK_3 CHECK (CONDITION BETWEEN 1 AND 5),
    CONSTRAINT BOOKS_CK_4 CHECK (BUY_DATE >= DATE '2022-09-01')
);

CREATE OR REPLACE TRIGGER BOOKS_TRIG
BEFORE INSERT OR UPDATE ON BOOKS FOR EACH ROW
DECLARE
    AUDIT_COL_INTERFERE EXCEPTION;
BEGIN
    IF 
        :NEW.WHO_ADDED != nvl(:OLD.WHO_ADDED, USER) OR 
        :NEW.WHEN_ADDED != nvl(:OLD.WHEN_ADDED, SYSDATE) OR
        :NEW.WHO_LAST_MOD != nvl(:OLD.WHO_LAST_MOD, '234234234') OR
        :NEW.WHEN_LAST_MOD != nvl(:OLD.WHEN_LAST_MOD, sysdate-1) THEN
            RAISE AUDIT_COL_INTERFERE;
    END IF;
    
    IF INSERTING THEN 
        :NEW.WHO_ADDED := USER;
        :NEW.WHEN_ADDED := SYSDATE;
    ELSIF UPDATING THEN
        :NEW.WHO_ADDED := :OLD.WHO_ADDED;
        :NEW.WHEN_ADDED := :OLD.WHEN_ADDED;
        :NEW.WHO_LAST_MOD := USER;
        :NEW.WHEN_LAST_MOD := SYSDATE;
    END IF;
EXCEPTION
    WHEN AUDIT_COL_INTERFERE THEN
        RAISE_APPLICATION_ERROR(-20101, 'BOOKS TABLE: AN ATTEMPT TO INTERFERE WITH AN AUDIT COLUMN WAS MADE');
END;
/

-- =======================================================================

CREATE TABLE DELIVERIES(
    DELIVERY_ID NUMBER(10) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    DELIVERY_DATE DATE DEFAULT SYSDATE NOT NULL,
    TITLE_ID NUMBER(10) NOT NULL,
    AMOUNT NUMBER(10) DEFAULT 1 NOT NULL,
    WHO_ADDED VARCHAR2(70) DEFAULT USER NOT NULL,
    WHEN_ADDED TIMESTAMP DEFAULT SYSDATE NOT NULL,
    WHO_LAST_MOD VARCHAR2(70) NULL,
    WHEN_LAST_MOD TIMESTAMP NULL,
    CONSTRAINT DELIVERIES_PK PRIMARY KEY (DELIVERY_ID)
);

CREATE OR REPLACE TRIGGER DELIVERIES_TRIG
BEFORE INSERT OR UPDATE ON DELIVERIES FOR EACH ROW
DECLARE
    AUDIT_COL_INTERFERE EXCEPTION;
BEGIN
    IF 
        :NEW.WHO_ADDED != nvl(:OLD.WHO_ADDED, USER) OR 
        :NEW.WHEN_ADDED != nvl(:OLD.WHEN_ADDED, SYSDATE) OR
        :NEW.WHO_LAST_MOD != nvl(:OLD.WHO_LAST_MOD, '234234234') OR
        :NEW.WHEN_LAST_MOD != nvl(:OLD.WHEN_LAST_MOD, sysdate-1) THEN
            RAISE AUDIT_COL_INTERFERE;
    END IF;
    
    IF INSERTING THEN 
        :NEW.WHO_ADDED := USER;
        :NEW.WHEN_ADDED := SYSDATE;
    ELSIF UPDATING THEN
        :NEW.WHO_ADDED := :OLD.WHO_ADDED;
        :NEW.WHEN_ADDED := :OLD.WHEN_ADDED;
        :NEW.WHO_LAST_MOD := USER;
        :NEW.WHEN_LAST_MOD := SYSDATE;
    END IF;
EXCEPTION
    WHEN AUDIT_COL_INTERFERE THEN
        RAISE_APPLICATION_ERROR(-20101, 'DELIVERIES TABLE: AN ATTEMPT TO INTERFERE WITH AN AUDIT COLUMN WAS MADE');
END;
/

-- =======================================================================

CREATE TABLE ADDRESSES(
    ADDRESS_ID NUMBER(10) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    POSTAL_CODE VARCHAR2(10) NOT NULL,
    POSTAL_CITY VARCHAR2(70) NOT NULL,
    CITY VARCHAR2(70) NOT NULL,
    STREET VARCHAR2(70) NULL,
    HOUSE_NO VARCHAR2(70) NOT NULL,
    FLAT_NO VARCHAR2(10) NULL,
    NOTES VARCHAR2(4000) NULL,
    WHO_ADDED VARCHAR2(70) DEFAULT USER NOT NULL,
    WHEN_ADDED TIMESTAMP DEFAULT SYSDATE NOT NULL,
    WHO_LAST_MOD VARCHAR2(70) NULL,
    WHEN_LAST_MOD TIMESTAMP NULL,
    CONSTRAINT ADDRESSES_PK PRIMARY KEY (ADDRESS_ID)
);

CREATE OR REPLACE TRIGGER ADDRESSES_TRIG
BEFORE INSERT OR UPDATE ON ADDRESSES FOR EACH ROW
DECLARE
    AUDIT_COL_INTERFERE EXCEPTION;
BEGIN
    IF 
        :NEW.WHO_ADDED != nvl(:OLD.WHO_ADDED, USER) OR 
        :NEW.WHEN_ADDED != nvl(:OLD.WHEN_ADDED, SYSDATE) OR
        :NEW.WHO_LAST_MOD != nvl(:OLD.WHO_LAST_MOD, '234234234') OR
        :NEW.WHEN_LAST_MOD != nvl(:OLD.WHEN_LAST_MOD, sysdate-1) THEN
            RAISE AUDIT_COL_INTERFERE;
    END IF;
    
    IF INSERTING THEN 
        :NEW.WHO_ADDED := USER;
        :NEW.WHEN_ADDED := SYSDATE;
    ELSIF UPDATING THEN
        :NEW.WHO_ADDED := :OLD.WHO_ADDED;
        :NEW.WHEN_ADDED := :OLD.WHEN_ADDED;
        :NEW.WHO_LAST_MOD := USER;
        :NEW.WHEN_LAST_MOD := SYSDATE;
    END IF;
EXCEPTION
    WHEN AUDIT_COL_INTERFERE THEN
        RAISE_APPLICATION_ERROR(-20101, 'ADDRESSES TABLE: AN ATTEMPT TO INTERFERE WITH AN AUDIT COLUMN WAS MADE');
END;
/

-- =======================================================================

CREATE TABLE ADDRESSES_READERS(
    ADDRESS_ID NUMBER(10) NOT NULL,
    READER_ID NUMBER(10) NOT NULL,
    WHO_ADDED VARCHAR2(70) DEFAULT USER NOT NULL,
    WHEN_ADDED TIMESTAMP DEFAULT SYSDATE NOT NULL,
    WHO_LAST_MOD VARCHAR2(70) NULL,
    WHEN_LAST_MOD TIMESTAMP NULL,
    CONSTRAINT ADDRESSES_READERS_PK PRIMARY KEY (ADDRESS_ID, READER_ID),
    CONSTRAINT ADDRESSES_READERS_FK_1 FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESSES(ADDRESS_ID),
    CONSTRAINT ADDRESSES_READERS_FK_2 FOREIGN KEY (READER_ID) REFERENCES READERS(READER_ID)
);

CREATE OR REPLACE TRIGGER ADDRESSES_READERS_TRIG
BEFORE INSERT OR UPDATE ON ADDRESSES_READERS FOR EACH ROW
DECLARE
    AUDIT_COL_INTERFERE EXCEPTION;
BEGIN
    IF 
        :NEW.WHO_ADDED != nvl(:OLD.WHO_ADDED, USER) OR 
        :NEW.WHEN_ADDED != nvl(:OLD.WHEN_ADDED, SYSDATE) OR
        :NEW.WHO_LAST_MOD != nvl(:OLD.WHO_LAST_MOD, '234234234') OR
        :NEW.WHEN_LAST_MOD != nvl(:OLD.WHEN_LAST_MOD, sysdate-1) THEN
            RAISE AUDIT_COL_INTERFERE;
    END IF;
    
    IF INSERTING THEN 
        :NEW.WHO_ADDED := USER;
        :NEW.WHEN_ADDED := SYSDATE;
    ELSIF UPDATING THEN
        :NEW.WHO_ADDED := :OLD.WHO_ADDED;
        :NEW.WHEN_ADDED := :OLD.WHEN_ADDED;
        :NEW.WHO_LAST_MOD := USER;
        :NEW.WHEN_LAST_MOD := SYSDATE;
    END IF;
EXCEPTION
    WHEN AUDIT_COL_INTERFERE THEN
        RAISE_APPLICATION_ERROR(-20101, 'ADDRESSES_READERS TABLE: AN ATTEMPT TO INTERFERE WITH AN AUDIT COLUMN WAS MADE');
END;
/

-- =======================================================================

CREATE TABLE READERS(
    READER_ID NUMBER(10) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    FIRST_NAMES VARCHAR2(100) NULL,
    LAST_NAMES VARCHAR2(100) NOT NULL,
    JOIN_DATE DATE NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(70) NOT NULL,
    PESEL VARCHAR2(11) NULL,
    DEFAULT_ADDRESS NUMBER(10) NOT NULL,
    WHO_ADDED VARCHAR2(70) DEFAULT USER NOT NULL,
    WHEN_ADDED TIMESTAMP DEFAULT SYSDATE NOT NULL,
    WHO_LAST_MOD VARCHAR2(70) NULL,
    WHEN_LAST_MOD TIMESTAMP NULL,
    CONSTRAINT READERS_PK PRIMARY KEY (READER_ID),
    CONSTRAINT READERS_FK_1 FOREIGN KEY (DEFAULT_ADDRESS) REFERENCES ADDRESSES (ADDRESS_ID),
    CONSTRAINT READERS_CK_1 CHECK (JOIN_DATE > BIRTH_DATE)
);

CREATE OR REPLACE TRIGGER READERS_TRIG
BEFORE INSERT OR UPDATE ON READERS FOR EACH ROW
DECLARE
    AUDIT_COL_INTERFERE EXCEPTION;
BEGIN
    IF 
        :NEW.WHO_ADDED != nvl(:OLD.WHO_ADDED, USER) OR 
        :NEW.WHEN_ADDED != nvl(:OLD.WHEN_ADDED, SYSDATE) OR
        :NEW.WHO_LAST_MOD != nvl(:OLD.WHO_LAST_MOD, '234234234') OR
        :NEW.WHEN_LAST_MOD != nvl(:OLD.WHEN_LAST_MOD, sysdate-1) THEN
            RAISE AUDIT_COL_INTERFERE;
    END IF;
    
    IF INSERTING THEN 
        :NEW.WHO_ADDED := USER;
        :NEW.WHEN_ADDED := SYSDATE;
    ELSIF UPDATING THEN
        :NEW.WHO_ADDED := :OLD.WHO_ADDED;
        :NEW.WHEN_ADDED := :OLD.WHEN_ADDED;
        :NEW.WHO_LAST_MOD := USER;
        :NEW.WHEN_LAST_MOD := SYSDATE;
    END IF;
EXCEPTION
    WHEN AUDIT_COL_INTERFERE THEN
        RAISE_APPLICATION_ERROR(-20101, 'READERS TABLE: AN ATTEMPT TO INTERFERE WITH AN AUDIT COLUMN WAS MADE');
END;
/

-- =======================================================================

CREATE TABLE BORROWS(
    BORROW_ID NUMBER(10) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    BOOK_ID NUMBER(10) NOT NULL,
    READER_ID NUMBER(10) NOT NULL,
    START_DATE DATE NOT NULL,
    WHO_ADDED VARCHAR2(70) DEFAULT USER NOT NULL,
    WHEN_ADDED TIMESTAMP DEFAULT SYSDATE NOT NULL,
    WHO_LAST_MOD VARCHAR2(70) NULL,
    WHEN_LAST_MOD TIMESTAMP NULL,
    CONSTRAINT BORROWS_PK PRIMARY KEY (BORROW_ID),
    CONSTRAINT BORROWS_FK_1 FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID),
    CONSTRAINT BORROWS_FK_2 FOREIGN KEY (READER_ID) REFERENCES READERS(READER_ID)
);

CREATE OR REPLACE TRIGGER BORROWS_TRIG
BEFORE INSERT OR UPDATE ON BORROWS FOR EACH ROW
DECLARE
    AUDIT_COL_INTERFERE EXCEPTION;
BEGIN
    IF 
        :NEW.WHO_ADDED != nvl(:OLD.WHO_ADDED, USER) OR 
        :NEW.WHEN_ADDED != nvl(:OLD.WHEN_ADDED, SYSDATE) OR
        :NEW.WHO_LAST_MOD != nvl(:OLD.WHO_LAST_MOD, '234234234') OR
        :NEW.WHEN_LAST_MOD != nvl(:OLD.WHEN_LAST_MOD, sysdate-1) THEN
            RAISE AUDIT_COL_INTERFERE;
    END IF;
    
    IF INSERTING THEN 
        :NEW.WHO_ADDED := USER;
        :NEW.WHEN_ADDED := SYSDATE;
    ELSIF UPDATING THEN
        :NEW.WHO_ADDED := :OLD.WHO_ADDED;
        :NEW.WHEN_ADDED := :OLD.WHEN_ADDED;
        :NEW.WHO_LAST_MOD := USER;
        :NEW.WHEN_LAST_MOD := SYSDATE;
    END IF;
EXCEPTION
    WHEN AUDIT_COL_INTERFERE THEN
        RAISE_APPLICATION_ERROR(-20101, 'BORROWS TABLE: AN ATTEMPT TO INTERFERE WITH AN AUDIT COLUMN WAS MADE');
END;
/

-- =======================================================================

CREATE TABLE H_BORROWS(
    BORROW_ID NUMBER(10) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    BOOK_ID NUMBER(10) NOT NULL,
    READER_ID NUMBER(10) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    BORROW_RESULT VARCHAR2(70) NOT NULL,
    CONDITION_CHANGE NUMBER(1) NOT NULL,
    WHO_ADDED VARCHAR2(70) DEFAULT USER NOT NULL,
    WHEN_ADDED TIMESTAMP DEFAULT SYSDATE NOT NULL,
    WHO_LAST_MOD VARCHAR2(70) NULL,
    WHEN_LAST_MOD TIMESTAMP NULL,
    CONSTRAINT H_BORROWS_PK PRIMARY KEY (BORROW_ID),
    CONSTRAINT H_BORROWS_FK_1 FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID),
    CONSTRAINT H_BORROWS_FK_2 FOREIGN KEY (READER_ID) REFERENCES READERS(READER_ID),
    CONSTRAINT H_BORROWS_CK_1 CHECK (START_DATE <= END_DATE),
    CONSTRAINT H_BORROWS_CK_2 CHECK (BORROW_RESULT IN ('RETURNED', 'LOST OR DESTROYED')),
    CONSTRAINT H_BORROWS_CK_3 CHECK (CONDITION_CHANGE BETWEEN -4 AND 0)
);

CREATE OR REPLACE TRIGGER H_BORROWS_TRIG
BEFORE INSERT OR UPDATE ON H_BORROWS FOR EACH ROW
DECLARE
    AUDIT_COL_INTERFERE EXCEPTION;
BEGIN
    IF 
        :NEW.WHO_ADDED != nvl(:OLD.WHO_ADDED, USER) OR 
        :NEW.WHEN_ADDED != nvl(:OLD.WHEN_ADDED, SYSDATE) OR
        :NEW.WHO_LAST_MOD != nvl(:OLD.WHO_LAST_MOD, '234234234') OR
        :NEW.WHEN_LAST_MOD != nvl(:OLD.WHEN_LAST_MOD, sysdate-1) THEN
            RAISE AUDIT_COL_INTERFERE;
    END IF;
    
    IF INSERTING THEN 
        :NEW.WHO_ADDED := USER;
        :NEW.WHEN_ADDED := SYSDATE;
    ELSIF UPDATING THEN
        :NEW.WHO_ADDED := :OLD.WHO_ADDED;
        :NEW.WHEN_ADDED := :OLD.WHEN_ADDED;
        :NEW.WHO_LAST_MOD := USER;
        :NEW.WHEN_LAST_MOD := SYSDATE;
    END IF;
EXCEPTION
    WHEN AUDIT_COL_INTERFERE THEN
        RAISE_APPLICATION_ERROR(-20101, 'H_BORROWS TABLE: AN ATTEMPT TO INTERFERE WITH AN AUDIT COLUMN WAS MADE');
END;
/