CREATE OR REPLACE PACKAGE RENTAL AS

    TYPE ID_ARRAY IS TABLE OF NUMBER(10);
    
    TYPE AUTHOR_RECORD IS RECORD (FIRST_NAME VARCHAR2(100), LAST_NAME MK.AUTHORS.LAST_NAME%TYPE, BIRTH_DATE DATE, DEATH_DATE DATE);
    
    TYPE AUTHORS IS TABLE OF AUTHOR_RECORD;
    
    TYPE TITLE_RECORD IS RECORD (TITLE VARCHAR2(250), PUB_DATE DATE, AGE_LIMIT NUMBER(2), TITLE_DESCRIPTION BLOB);
    
    TYPE AUTHOR_TITLE_RECORD IS RECORD (AUTHOR_ID NUMBER(10), TITLE_ID NUMBER(10));
    
    TYPE LOCATION_SPOTS IS RECORD (LOCATION_ID NUMBER(10), NUMBER_OF_EMPTY_SPOTS NUMBER);
    
    TYPE LOCATIONS_DICTIONARY IS TABLE OF LOCATION_SPOTS;
    
    TYPE DELIVERY_PART IS RECORD (
                                  T_AUTHORS AUTHORS
                                 ,T_TITLE TITLE_RECORD
                                 ,T_AMOUNT NUMBER
                                 ,T_ADDED_BOOKS_VALUE NUMBER
                                 ,T_ADDED_BOOKS_CONDITION NUMBER
                                 ,T_ADDED_BOOKS_BUY_DATE DATE);
                                 
    TYPE DELIVERY_DICTIONARY IS TABLE OF DELIVERY_PART;
    
    LOCATIONS_CORRIDOR_NUMBER CONSTANT NUMBER := 10;
    LOCATIONS_RACK_NUMBER CONSTANT NUMBER := 15;
    LOCATIONS_SHELF_NUMBER CONSTANT NUMBER := 8;
    LOCATIONS_BOOKS_ON_SHELF CONSTANT NUMBER := 12;
    
    TYPE BOOK_RECORD IS RECORD (TITLE_ID NUMBER, LOCATION_ID NUMBER, BOOK_VALUE NUMBER, CONDITION NUMBER, BUY_DATE DATE);
    
    TYPE BORROWS_RECORD IS RECORD (BORROW_ID NUMBER, BOOK_ID NUMBER, READER_ID NUMBER, START_DATE DATE);
    
    TYPE H_BORROWS_RECORD IS RECORD (BORROW_ID NUMBER, BOOK_ID NUMBER, READER_ID NUMBER,
        START_DATE DATE, END_DATE DATE, BORROW_RESULT VARCHAR2(70), CONDITION_CHANGE NUMBER);
    
    TYPE ADDRESS_RECORD IS RECORD (ADDRESS_ID NUMBER, POSTAL_CODE VARCHAR2(10), POSTAL_CITY VARCHAR2(70), 
        CITY VARCHAR2(70), STREET VARCHAR2(70), HOUSE_NO VARCHAR2(10), FLAT_NO VARCHAR2(10), NOTES VARCHAR2(2000));
        
    TYPE ADDRESS_READER_RECORD IS RECORD (ADDRESS_ID NUMBER, READER_ID NUMBER);
    
    TYPE READER_RECORD IS RECORD (READER_ID NUMBER, FIRST_NAMES VARCHAR2(100), LAST_NAMES VARCHAR2(100),
        JOIN_DATE DATE, BIRTH_DATE DATE, PHONE VARCHAR2(20), EMAIL VARCHAR2(70), PESEL VARCHAR2(11),
        DEFAULT_ADDRESS NUMBER);
    
    -- ==================================================================
    
    FUNCTION DELIVERY (T_DELIVERY_DICTIONARY DELIVERY_DICTIONARY) RETURN ID_ARRAY;
    
    FUNCTION DELIVERY (T_DELIVERY_PART DELIVERY_PART) RETURN ID_ARRAY;

    FUNCTION SEARCH_AUTHOR (AUTHOR_TO_SEARCH AUTHOR_RECORD) RETURN NUMBER;
    
    FUNCTION SEARCH_AUTHOR (FIRST_NAME VARCHAR2, LAST_NAME VARCHAR2, BIRTH_DATE DATE, DEATH_DATE DATE) 
        RETURN NUMBER;
    
    FUNCTION ADD_AUTHOR (AUTHOR_TO_ADD AUTHOR_RECORD) 
        RETURN NUMBER;
    
    FUNCTION ADD_AUTHOR (FIRST_NAME VARCHAR2, LAST_NAME VARCHAR2, BIRTH_DATE DATE, DEATH_DATE DATE) 
        RETURN NUMBER;
    
    FUNCTION PICK_AUTHOR (PICKED_AUTHOR_ID NUMBER, AUTHOR_TO_PICK AUTHOR_RECORD) 
        RETURN NUMBER;
        
    FUNCTION PICK_AUTHOR (PICKED_AUTHOR_ID NUMBER, FIRST_NAME VARCHAR2, LAST_NAME VARCHAR2, BIRTH_DATE DATE, DEATH_DATE DATE)
        RETURN NUMBER;
    
    FUNCTION SEARCH_TITLE (TITLE_TO_SEARCH TITLE_RECORD) 
        RETURN NUMBER;
        
    FUNCTION SEARCH_TITLE (TITLE VARCHAR2, PUB_DATE DATE, AGE_LIMIT NUMBER, TITLE_DESCRIPTION BLOB)
        RETURN NUMBER;
    
    FUNCTION ADD_TITLE (TITLE_TO_ADD TITLE_RECORD) 
        RETURN NUMBER;
        
    FUNCTION ADD_TITLE (TITLE VARCHAR2, PUB_DATE DATE, AGE_LIMIT NUMBER, TITLE_DESCRIPTION BLOB)
        RETURN NUMBER;
    
    FUNCTION PICK_TITLE (PICKED_TITLE_ID NUMBER, TITLE_TO_PICK TITLE_RECORD) 
        RETURN NUMBER;
        
    FUNCTION PICK_TITLE (PICKED_TITLE_ID NUMBER, TITLE VARCHAR2, PUB_DATE DATE, AGE_LIMIT NUMBER, TITLE_DESCRIPTION BLOB)
        RETURN NUMBER;
    
    FUNCTION AUTHORS_TITLES_RELATION (RELATION_AUTHORS ID_ARRAY, RELATION_TITLE_ID NUMBER) 
        RETURN NUMBER;
    
    PROCEDURE INITIATE_lOCATIONS;
    
    FUNCTION GET_LOCATION_LIST (BOOKS_AMOUNT NUMBER) 
        RETURN LOCATIONS_DICTIONARY;
    
    FUNCTION ADD_BOOKS (TITLE_ID NUMBER, ADDED_BOOKS_LOCATIONS LOCATIONS_DICTIONARY, HOW_MANY_BOOKS NUMBER,
        ADDED_BOOKS_VALUE NUMBER, ADDED_BOOKS_CONDITION NUMBER, ADDED_BOOKS_BUY_DATE DATE) 
        RETURN ID_ARRAY;
    
    FUNCTION LOCK_LOCATION (T_LOCATION_ID NUMBER, T_TIMEOUT INTEGER := 1) 
        RETURN INTEGER;
        
    FUNCTION RELEASE_LOCK_LOCATION (T_LOCATION_ID NUMBER)
        RETURN INTEGER;
        
    -- ==================================================================
        
    FUNCTION SEARCH_ADDRESS (T_ADDRESS_RECORD ADDRESS_RECORD)
        RETURN NUMBER;
        
    FUNCTION SEARCH_ADDRESS (ADDRESS_ID NUMBER, POSTAL_CODE VARCHAR2, POSTAL_CITY VARCHAR2, 
        CITY VARCHAR2, STREET VARCHAR2, HOUSE_NO VARCHAR2, FLAT_NO VARCHAR2, NOTES VARCHAR2)
        RETURN NUMBER;
        
    FUNCTION ADD_ADDRESS (T_ADDRESS_RECORD ADDRESS_RECORD)
        RETURN NUMBER;
        
    FUNCTION ADD_ADDRESS (ADDRESS_ID NUMBER, POSTAL_CODE VARCHAR2, POSTAL_CITY VARCHAR2, 
        CITY VARCHAR2, STREET VARCHAR2, HOUSE_NO VARCHAR2, FLAT_NO VARCHAR2, NOTES VARCHAR2)
        RETURN NUMBER;
        
    FUNCTION PICK_ADDRESS (T_ADDRESS_RECORD ADDRESS_RECORD)
        RETURN NUMBER;
        
    FUNCTION PICK_ADDRESS (ADDRESS_ID NUMBER, POSTAL_CODE VARCHAR2, POSTAL_CITY VARCHAR2, 
        CITY VARCHAR2, STREET VARCHAR2, HOUSE_NO VARCHAR2, FLAT_NO VARCHAR2, NOTES VARCHAR2)
        RETURN NUMBER;
        
    FUNCTION SEARCH_READER (T_READER_RECORD READER_RECORD)
        RETURN NUMBER;
        
    FUNCTION SEARCH_READER (READER_ID NUMBER, FIRST_NAMES VARCHAR2, LAST_NAMES VARCHAR2, 
        JOIN_DATE DATE, BIRTH_DATE DATE, PHONE VARCHAR2, EMAIL VARCHAR2, PESEL VARCHAR2,
        DEFAULT_ADDRESS NUMBER)
        RETURN NUMBER;
        
    FUNCTION ADD_READER (T_READER_RECORD READER_RECORD)
        RETURN NUMBER;
        
    FUNCTION ADD_READER (READER_ID NUMBER, FIRST_NAMES VARCHAR2, LAST_NAMES VARCHAR2, 
        JOIN_DATE DATE, BIRTH_DATE DATE, PHONE VARCHAR2, EMAIL VARCHAR2, PESEL VARCHAR2,
        DEFAULT_ADDRESS NUMBER)
        RETURN NUMBER;
        
    FUNCTION PICK_READER (T_READER_RECORD READER_RECORD)
        RETURN NUMBER;
        
    FUNCTION PICK_READER (READER_ID NUMBER, FIRST_NAMES VARCHAR2, LAST_NAMES VARCHAR2, 
        JOIN_DATE DATE, BIRTH_DATE DATE, PHONE VARCHAR2, EMAIL VARCHAR2, PESEL VARCHAR2,
        DEFAULT_ADDRESS NUMBER)
        RETURN NUMBER;
    
END RENTAL;
/