CREATE OR REPLACE PACKAGE RENTAL AS

    TYPE ID_ARRAY IS TABLE OF NUMBER(10);
    
    TYPE AUTHOR_RECORD IS RECORD(
        FIRST_NAME VARCHAR2(100),
        LAST_NAME VARCHAR2(100),
        BIRTH_DATE DATE,
        DEATH_DATE DATE
    );
    
    TYPE TITLE_RECORD IS RECORD(
        TITLE VARCHAR2(250),
        PUB_DATE DATE,
        AGE_LIMIT NUMBER(2),
        TITLE_DESCRIPTION BLOB
    );
    
    TYPE AUTHOR_TITLE_RECORD IS RECORD(
        AUTHOR_ID NUMBER(10),
        TITLE_ID NUMBER(10)
    );
    
    LOCATIONS_CORRIDOR_NUMBER CONSTANT NUMBER := 10;
    LOCATIONS_RACK_NUMBER CONSTANT NUMBER := 15;
    LOCATIONS_SHELF_NUMBER CONSTANT NUMBER := 8;
    LOCATIONS_BOOKS_ON_SHELF CONSTANT NUMBER := 12;

    FUNCTION SEARCH_AUTHOR(
        AUTHOR_TO_SEARCH AUTHOR_RECORD
    ) RETURN ID_ARRAY;
    
    FUNCTION ADD_AUTHOR(
        AUTHOR_TO_ADD AUTHOR_RECORD
    ) RETURN NUMBER;
    
    FUNCTION PICK_AUTHOR(
        PICKED_AUTHOR_ID NUMBER,
        AUTHOR_TO_PICK AUTHOR_RECORD
    ) RETURN NUMBER;
    
    FUNCTION ADD_TITLE(
        TITLE_TO_ADD TITLE_RECORD
    ) RETURN NUMBER;
    
    FUNCTION PICK_TITLE(
        PICKED_TITLE_ID NUMBER,
        TITLE_TO_PICK TITLE_RECORD
    ) RETURN NUMBER;
    
    FUNCTION AUTHORS_TITLES_RELATION(
        RELATION_AUTHORS ID_ARRAY,
        RELATION_TITLE_ID NUMBER
    ) RETURN NUMBER;
    
END RENTAL;
/



















